# -*- coding: utf-8 -*-
"""grp13_112_096_074.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/191UK2lOQZX18GDUjl3hfOR-NRjQm5Zts
"""

import pandas as pd              # Data manipulation and dataset handling
import numpy as np               # Numerical computations and array operations
import random                    # Setting seed for fixed data randomization
import matplotlib.pyplot as plt  # Core data visualization engine
import seaborn as sns            # Advanced statistical plotting (heatmaps, box plots, etc.)
import scipy.stats as stats      # Statistical hypothesis testing (t-tests, normality tests)
import statsmodels.api as sm     # Regression modeling (linear & logistic regressions)
import urllib.request            # Python built-in module to fetch endpoint IP for localtunnel

# Use the /export?format=csv URL instead of /edit
sheet_url = 'https://docs.google.com/spreadsheets/d/1GwrWQcp17kluJOW_7_ODe60AbWofQY1_nKY49ekF6p0/export?format=csv&gid=0'
df = pd.read_csv(sheet_url)

random_seed = 112096074
random.seed(random_seed)
np.random.seed(random_seed)

# Sampling exactly 2501 records
grp13_112_096_074 = df.sample(n=2501, random_state=random_seed)

# Saving with a new custom name
grp13_112_096_074.to_csv('grp13_sampled_data.csv', index=False)

print(f"Successfully sampled {len(grp13_112_096_074)} records!")

# 1. Descriptive Statistics (Measures of Central Tendency, Dispersion, Skewness, Kurtosis)
print("--- Descriptive Statistics ---")
display(grp13_112_096_074.describe())
print("\nSkewness:\n", grp13_112_096_074.select_dtypes(include=np.number).skew())
print("\nKurtosis:\n", grp13_112_096_074.select_dtypes(include=np.number).kurtosis())

# Categorical Data Frequencies
print("\n--- Categorical Data (Gender Frequency) ---")
display(grp13_112_096_074['gender'].value_counts(normalize=True) * 100)

# 2. Measures of Correlation (Pearson)
print("\n--- Correlation Matrix ---")
numeric_cols = ['age', 'monthly_fee', 'csat_score', 'tenure_months']
correlation_matrix = grp13_112_096_074[numeric_cols].corr()
display(correlation_matrix)

# 3. Visualizations (Heat Map, Scatter Plot, Box-Whisker)
plt.figure(figsize=(15, 4))

# Heat Map
plt.subplot(1, 3, 1)
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heat Map')

# Scatter Plot
plt.subplot(1, 3, 2)
sns.scatterplot(x='monthly_fee', y='csat_score', data=grp13_112_096_074)
plt.title('Monthly Fee vs CSAT Score')

# Box-Whisker Plot
plt.subplot(1, 3, 3)
sns.boxplot(x='churn', y='age', data=grp13_112_096_074)
plt.title('Age by Churn Status')
plt.tight_layout()
plt.show()

# 4. Inferential Statistics (Test of Normality & T-Test)
print("\n--- Inferential Statistics ---")
# Shapiro-Wilk Test for Normality on Age
stat, p = stats.shapiro(grp13_112_096_074['age'].dropna())
print(f"Shapiro-Wilk Test for Age - Statistic: {stat:.4f}, P-value: {p:.4e}")

# 5. Causal Analysis (Linear and Logistic Regression)
print("\n--- Causal Analysis (Regressions) ---")

# Linear Regression: Predicting CSAT Score based on Monthly Fee and Age
X_lin = grp13_112_096_074[['monthly_fee', 'age']]
X_lin = sm.add_constant(X_lin) # Adds a constant term to the predictor
y_lin = grp13_112_096_074['csat_score']
linear_model = sm.OLS(y_lin, X_lin, missing='drop').fit()
print(linear_model.summary())

# Logistic Regression: Predicting Churn (0 or 1) based on Tenure and Monthly Fee
X_log = grp13_112_096_074[['tenure_months', 'monthly_fee']]
X_log = sm.add_constant(X_log)
y_log = grp13_112_096_074['churn']
log_model = sm.Logit(y_log, X_log, missing='drop').fit(disp=0)
print(log_model.summary())

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# st.title("Customer Churn Analytical Dashboard")
# st.write("Group ID: 112_096_074")
# 
# # Load the newly named sampled data
# grp13_112_096_074 = pd.read_csv('grp13_sampled_data.csv')
# 
# if st.checkbox("Show Raw Data"):
#     st.write(grp13_112_096_074.head())
# 
# st.sidebar.header("Filter Options")
# # Using lowercase 'gender'
# selected_gender = st.sidebar.selectbox("Select Gender", grp13_112_096_074['gender'].unique())
# filtered_df = grp13_112_096_074[grp13_112_096_074['gender'] == selected_gender]
# 
# st.subheader(f"Age Distribution for {selected_gender}")
# fig, ax = plt.subplots()
# # Using lowercase 'age'
# sns.histplot(filtered_df['age'], ax=ax, kde=True)
# st.pyplot(fig)

# 1. Install streamlit and localtunnel
pip install -q streamlit
npm install -g localtunnel

# 2. Get the IP address for the password screen
import urllib
print("Password/Endpoint IP:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))

# 3. Run Streamlit and force localtunnel to bypass the "y/n" prompt
!streamlit run app.py & npx -y localtunnel --port 8501
